### ISSUE TITLE
Get the list of book categories in the library management system.

### ISSUE THREAD

**Issue by chinthakarukshan** [chinthakarukshan/lbms#10]
As an administrator, I need to get the list of book categories available in the library management system.

Following are the sub tasks for this user story.

- [x] Design the API for get list of book categories https://github.com/chinthakarukshan/lbms/issues/11
- [x] Develop API to get list of book categories https://github.com/chinthakarukshan/lbms-admin-service/issues/8
- [x] Write unit tests for the get list of book categories API https://github.com/chinthakarukshan/lbms-admin-service/issues/9

**Comment by chinthakarukshan** [comment]
All the sub tasks of this user story are completed. Therefore, closing this story.
