### ISSUE TITLE
Get Category by ID 

### ISSUE THREAD

**Issue by chinthakarukshan** [chinthakarukshan/lbms#12]
As an administrator of the library management system, I need to get the details of a book category using the ID of the category. Below are the three sub tasks which needs to be attended to complete this user story.

- [x] Design get category by category id API specification - https://github.com/chinthakarukshan/lbms/issues/13
- [x] Implement the get Category by ID API - https://github.com/chinthakarukshan/lbms-admin-service/issues/10
- [x] Write Unit Tests to the get category by ID API - https://github.com/chinthakarukshan/lbms-admin-service/issues/11

**Comment by chinthakarukshan** [comment]
This user story is completed after implementing the sub tasks associated with this.
