### ISSUE TITLE
Update a Category in the Library Management Service

### ISSUE THREAD

**Issue by chinthakarukshan** [chinthakarukshan/lbms#14]
As an administrator of the library management system, I need to update a category in the library management system. The update should only allow to change the status of the category. Changing the category name and description are not allowed.

- [x] Design the category update API specification - https://github.com/chinthakarukshan/lbms/issues/15
- [x] Implement the category update API - https://github.com/chinthakarukshan/lbms-admin-service/issues/12
- [x] Write Unit Tests for the category update API - https://github.com/chinthakarukshan/lbms-admin-service/issues/13

**Comment by chinthakarukshan** [comment]
Completed user story
