### ISSUE TITLE
Add Author to the Library Management System

### ISSUE THREAD

**Issue by chinthakarukshan** [chinthakarukshan/lbms#16]
Administrator needs to add authors to the library management system in order to manage the book entries in the system. Following tasks are identified as the tasks to complete this user story.

- [x] Design the add author API Specification  https://github.com/chinthakarukshan/lbms/issues/17
- [x] Implement add author API - https://github.com/chinthakarukshan/lbms-admin-service/issues/14
- [x] Write unit tests to the add author API - https://github.com/chinthakarukshan/lbms-admin-service/issues/15

**Comment by chinthakarukshan** [comment]
User Story Completed
