### ISSUE TITLE
Get the list of Authors in the Library Management System

### ISSUE THREAD

**Issue by chinthakarukshan** [chinthakarukshan/lbms#18]
Get the available list of authors in the library management system in order to manage the authors. Following tasks needs to complete in order to complete this user story.

- [x] Design the get list of author API specification - https://github.com/chinthakarukshan/lbms/issues/19
- [ ] Implement API to get list of authors - https://github.com/chinthakarukshan/lbms-admin-service/issues/17
- [ ] Write unit tests to get list of authors API - https://github.com/chinthakarukshan/lbms-admin-service/issues/16
