### ISSUE TITLE
Get the details of an Author 

### ISSUE THREAD

**Issue by chinthakarukshan** [chinthakarukshan/lbms#20]
As the administrator, I need to get the details of the author in order to manage the authors details. To complete this story, following sub tasks needs to be completed.

- [ ] Design the API specification for get author information API - https://github.com/chinthakarukshan/lbms/issues/21
- [ ] Implement the get author information API - https://github.com/chinthakarukshan/lbms-admin-service/issues/18
- [ ] Write unit tests for teh get author information API  - https://github.com/chinthakarukshan/lbms-admin-service/issues/19
