### ISSUE TITLE
Updating the member details in the Library management System

### ISSUE THREAD

**Issue by chinthakarukshan** [chinthakarukshan/lbms#3]
As an administrator I need to update the details of the members in the library management System.

Following tasks has to be attended to complete this user story.

- [x] Design the Patch Member API https://github.com/chinthakarukshan/lbms/issues/4
- [x] Implement the Patch Member API https://github.com/chinthakarukshan/lbms-admin-service/issues/3
- [x] Writing Unit Tests for Patch Member API https://github.com/chinthakarukshan/lbms-admin-service/issues/5

**Comment by chinthakarukshan** [comment]
Story completed.
