### ISSUE TITLE
Add a new Book Category to the Library Management System

### ISSUE THREAD

**Issue by chinthakarukshan** [chinthakarukshan/lbms#8]
As an administrator of the library management system I need to add a new book category to the library management system. Below list of tasks need to be completed in order to complete this user story.

- [x] Design API for Book Category Management Post Request https://github.com/chinthakarukshan/lbms/issues/9
- [x] Implement the API for Book Category Post https://github.com/chinthakarukshan/lbms-admin-service/issues/6
- [x] Implement unit tests for the category management post API https://github.com/chinthakarukshan/lbms-admin-service/issues/7

**Comment by chinthakarukshan** [comment]
Implementations of this user story is completed
